Gumigram/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.chg_pw, name='chg_pw'),
]

Gumigram/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

Gumigram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gumigram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://use.typekit.net/usr7mmc.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script>
    (function(d) {
      var config = {
        kitId: 'lpb6eir',
        scriptTimeout: 3000,
        async: true
      },
      h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
    })(document);
  </script>
</head>
<body class="bg-dark">
  {% if messages %}
      {% for message in messages %}
        <div class="alert fade show alert-{{ message.tags }} py-1 d-flex justify-content-between" role="alert">
          <div>{{ message }}</div>
          <div><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>
        </div>
      {% endfor %}
  {% endif %}

  <div class="container">
    {% include "nav.html" %}

    <div class="container pb-3 px-4">
      {% block content %}

      {% endblock content %}
    </div>
  </div>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

Gumigram/templates/nav.html
{% load static %}

<nav class="navbar navbar-expand navbar-dark bg-dark sticky-top">
  <div class="container-fluid text-white px-0">
    <a class="navbar-brand" href="{% url 'articles:index' %}">
      <h1 class="" style="font-size: 3rem;font-family: pique-web, snas-serif; background: linear-gradient(to right, #fbcac9, #8ca6ce); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
        Diacret.
      </h1>
    </a>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
      <div class="mx-2 d-flex">
        {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav" style="font-family: sandoll-ongothic, sans-serif;">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-white py-0" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.username }} <i class="fas fa-user fa-lg ms-1"></i>
                  </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink" style="font-family: sandoll-ongothic, sans-serif;">
                      <li><a class="dropdown-item" href="{% url 'accounts:update' %}">정보수정</a></li>
                      <li><form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <button class="dropdown-item">로그아웃</button>
                      </form></li>
                      <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">회원탈퇴</a></li>
                    </ul>
                </li>
              </ul>
          </div>
          <a class="nav-link text-decoration-none text-white p-2" aria-current="page" href="{% url 'articles:index' %}"><i class="fab fa-viadeo-square fa-3x" style="background: linear-gradient(to right, #fbcac9, #8ca6ce); -webkit-background-clip: text; -webkit-text-fill-color: transparent;"></i></a>
          <a class="nav-link text-decoration-none text-white p-2" href="{% url 'articles:create' %}"><i class="fas fa-pen-square fa-3x" style="background: linear-gradient(to right, #fbcac9, #8ca6ce); -webkit-background-clip: text; -webkit-text-fill-color: transparent;"></i></a>
        {% else %}
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="far fa-user fa-lg"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink" style="font-family: sandoll-ongothic, sans-serif;">
                  <li><a class="dropdown-item" href="{% url 'accounts:login' %}">로그인</a></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">회원가입</a></li>
                </ul>
              </li>
            </ul>
          </div>
        {% endif %}
      </div>
      <form class="d-flex">
        <input class="form-control me-2 bg-dark text-white py-1 d-none d-lg-inline" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary  py-1 d-none d-lg-inline" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered text-white" style="font-family: sandoll-ongothic, sans-serif;">
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">경고</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        정말 회원탈퇴를 진행하시겠습니까?
      </div>
      <div class="modal-footer">
        <form action="{% url 'accounts:delete' %}" method="POST">
          {% csrf_token %}
          <button type="button" class="btn btn-secondary pb-0 pt-1" data-bs-dismiss="modal" style="width: 2.5rem;"><i class="fas fa-times"></i></button>
          <button class="btn btn-outline-danger pb-0 pt-1" style="width: 2.5rem; padding-left: 0.6rem;"><i class="fas fa-user-slash"></i></button>
        </form>
      </div>
    </div>
  </div>
</div>