Gumigram/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

Gumigram/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gumigram/articles/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField, TextField
from django.db.models.fields.files import ImageField
from imagekit import processors
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.
class Article(models.Model):
    title = CharField(max_length=100)
    content = TextField()
    image = ImageField(blank=True, upload_to='%Y/%m/%d')
    img_thumb = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 200)],
        format='PNG',
        options={
            'quality':90,
        }
    )
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

Gumigram/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='TITLE :',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3 text-white bg-secondary',
                'placeholder': 'Enter the title',
                'style': 'font-family: paralucent, sans-serif;',
            }
        )
    )

    content = forms.CharField(
        label='CONTENT :',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control mb-3 text-white bg-secondary',
                'placeholder': 'Enter the content',
                'style': 'font-family: paralucent, sans-serif;',
            }
        )
    )

    image = forms.ImageField(
        label='IMAGE ',
        allow_empty_file=True,
        widget=forms.FileInput(
            attrs={
                'type': 'file',
                'accept': 'image/*',
                'style': 'font-family: paralucent, sans-serif;',
            }
        )
    )
    class Meta:
        model = Article
        fields = '__all__'

Gumigram/articles/views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Article
from .forms import ArticleForm

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.all()
    paginator = Paginator(articles, 9)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        # 'articles': articles,
        'page_obj': page_obj,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            messages.add_message(request, messages.INFO, '게시물이 등록되었습니다.')
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form':form
    }
    return render(request, 'articles/form.html', context)


@login_required
@require_safe
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save()
            messages.success(request, '게시물이 수정되었습니다.')
            return redirect('articles:detail', pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/form.html', context)


@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        article.delete()
        messages.error(request, '게시물이 삭제되었습니다.')
    return redirect('articles:index')

Gumigram/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="card bg-secondary mt-3">
    <div class="card-body">
      <div class="text-white h-100" style="font-family: sandoll-ongothic, sans-serif;">
        <h2>제목 : {{ article.title }}</h2>
        <hr>
        <h4>{{ article.content|linebreaks }}</h4>
        <img src="{{ article.image.url }}" alt="{{ article.image }}" class="w-100 mb-3">
        <p class="mb-0 fw-normal">작 성 : {{ article.created_at|date:"Y년 n월 j일 g:i A"}}</p>
        <p class="fw-normal">수 정 : {{ article.updated_at|date:"Y년 n월 j일 g:i A" }}</p>
        <hr>
        <form action="{% url 'articles:delete' article.pk %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="text-end">
            <a href="{% url 'articles:update' article.pk %}" class="btn btn-dark pb-0 pt-1 mb-3" style="width: 2.5rem;"><i class="fas fa-pen"></i></a>
            <button type="button" class="btn btn-outline-danger pb-0 pt-1 mb-3" data-bs-toggle="modal" data-bs-target="#exampleModal2" style="width: 2.5rem;">
              <i class="fas fa-trash"></i>
            </button>
            <a href="{% url 'articles:index' %}" class="btn btn-outline-dark px-2 pb-0 pt-1 mb-3 text-white" style="width: 2.5rem;"><i class="fas fa-undo-alt"></i></a>

            {% comment %} <a href="{% url 'articles:update' article.pk %}" class="text-decoration-none text-white"><i class="fas fa-pen-square fa-2x"></i></a>
            <a href="{% url 'articles:update' article.pk %}" class="btn btn-dark pb-0 pt-1 mb-3">수 정</a>
            <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" class="text-decoration-none text-white"><i class="fas fa-window-close fa-2x"></i></a>
            <button type="button" class="btn btn-dark pb-0 pt-1 mb-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
              삭 제
            </button>
            <a href="{% url 'articles:index' %}" class="btn btn-outline-dark pb-0 pt-1 mb-3">뒤 로</a> {% endcomment %}
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content bg-dark text-white fw-bold" style="font-family: sandoll-ongothic, sans-serif;">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">경고</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          게시물을 삭제하시겠습니까?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary pb-0 pt-1" data-bs-dismiss="modal"><i class="fas fa-times fa-lg"></i></button>
          <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-danger pb-0 pt-1"><i class="fas fa-trash"></i></button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

Gumigram/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="rounded bg-secondary mt-3 p-3 fw-bold">
    <form action="" method="POST" enctype="multipart/form-data" style="font-family: sandoll-ongothic, sans-serif;">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% comment %} {{ form }} {% endcomment %}
      <br>
    <div class="text-end">
      {% if article.pk %}
        <button class="btn btn-dark pb-0 pt-1" style="font-family: sandoll-ongothic, sans-serif;" style="width: 2.5rem;"><i class="fas fa-pen"></i></button>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-outline-danger pb-0 pt-1" style="width: 2.5rem;"><i class="fas fa-times fa-lg"></i></a>
        {% comment %} <button class="btn btn-dark pb-0 pt-1" style="font-family: sandoll-ongothic, sans-serif;">수 정</button>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-outline-dark pb-0 pt-1">취 소</a> {% endcomment %}
      {% else %}
        <button class='btn btn-dark pb-0 pt-1' style="width: 2.5rem;"><i class="fas fa-pen"></i></button>
        <a href="{% url 'articles:index' %}" class="btn btn-outline-danger pb-0 pt-1" style="width: 2.5rem;"><i class="fas fa-times fa-lg"></i></a>
        {% comment %} <button class='btn btn-dark pb-0 pt-1'>작 성</button>
        <a href="{% url 'articles:index' %}" class="btn btn-outline-dark pb-0 pt-1">뒤 로</a> {% endcomment %}
      {% endif %}
      </form>
    </div>
  </div>
{% endblock content %}

Gumigram/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
  <div class="row mb-3">
    {% for article in page_obj %}
      <div class="col-4 col text-center p-3">
        <div class="bg-secondary rounded">
          {% if article.image %}
            <a href="{% url 'articles:detail' article.pk %}"><img src="{{ article.img_thumb.url }}" class="card-img-top" alt="{{article.title}}"></a>
          {% else %}
            <img src="/static/GumiLogo.png" alt="" class="card-img-top">
          {% endif %}
          <div class="py-1">
            <h5 class="text-white m-0 fs-6" style="font-family: sandoll-ongothic, sans-serif;">{{ article.title|truncatechars:10 }}</h5>
          </div>
        </div>
      </div>
    {% empty %}
      <h3>No Content</h3>
    {% endfor %}
  </div>

  <div class="d-flex justify-content-center">
    {% bootstrap_pagination page_obj pages_to_show=5 %}
  </div>

{% endblock content %}